language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
addons:
  postgresql: "10.0"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
scripts:
  - bundle exec rspec spec
